# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACMaxPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_max_port', models.IntegerField(default=20000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('port', models.IntegerField()),
                ('password', models.CharField(max_length=64)),
                ('expired_date', models.DateTimeField()),
            ],
        ),
    ]
